### ISSUE TITLE
[PE-D][Tester E] Dates that are too far away are not handled

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-1/tp#221] opened 2024-11-08 22:40 UTC
I think it does not really make sense to have dates that are too far away. Maybe can try to handle it to be within a range of max 100 years?

![image.png](https://raw.githubusercontent.com/zi-yii/ped/main/files/20783fa0-b7bf-4f78-8f82-a3018724fdc6.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zi-yii/ped#17

**Comment by Jayden-Kim-NUS** [comment] 2024-11-09 06:16
All years from 0000 to 9999 are valid, as seen in the `YYYY` command format in the docs.
There is not much practical benefit to limiting the year to +-100 years other than to restrict the user.
Some users may want to use "9999-01-01" for an event which will happen in the future on 1st Jan but the year has not been confirmed yet.

Tester has labelled this `type.FunctionalityBug`.
It is most definitely not a bug as we did not mention anything about limits on dates far in the future in the docs.
This is intended behavior as the UG has outlined.
This will be closed as it is a non-issue.

**Closed by Jayden-Kim-NUS** 2024-11-09 06:16 UTC
Labels: Command
