### ISSUE TITLE
[PE-D][Tester B] Help Text for "edit e" command is incorrect

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-1/tp#188] opened 2024-11-08 17:59 UTC
When typing in the command `edit e`, the following help text is shown:

![image.png](https://raw.githubusercontent.com/brianchoon/ped/main/files/65988118-d258-47a8-aa22-7c402c8214ea.png)

In particular, `[s/PHONE]` is incorrect, it should be `[s/START TIME]`. This will align with your user guide too:

![image.png](https://raw.githubusercontent.com/brianchoon/ped/main/files/a7dac356-693c-4efa-83ab-37bd2da5ffd7.png)

I believe this is a very small error which will likely require a quick fix! Don't worry, it does not affect the functionality of your command!

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: brianchoon/ped#2

**Comment by Jayden-Kim-NUS** [comment] 2024-11-09 05:10
Duplicate of #174

**Closed by Jayden-Kim-NUS** 2024-11-09 05:10 UTC
Labels: Command
